[package]
name = "block-stm-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dashmap = "5.5.3"
rand = "0.8.5"
# TODO: Let's do our best to port needed changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "3c046a6aa734d914dc37bcade8ac5932a9599a23", features = [
    "serde-json",
] }
revme = { git = "https://github.com/risechain/revm", rev = "3c046a6aa734d914dc37bcade8ac5932a9599a23" }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = { version = "1.0.116", features = ["preserve_order"] }
thiserror = "1.0.59"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"

[profile.release]
debug = true
